compatibility_date = "2024-12-30"

compatibility_flags = [
  "nodejs_compat",
  "global_fetch_strictly_public",
]

[[workers]]
name = "tu-app-nextjs"
main = ".open-next/worker.js"
assets = { directory = ".open-next/assets", binding = "ASSETS" }


[[workers]]
name = "sanity-sync-webhook-worker"
main = "./workers/sanity-sync-webhook.ts"

[vars]