[pages]
pages_build_output_dir = ".open-next/assets"
compatibility_date = "2025-03-25"
compatibility_flags = [
  "nodejs_compat",
  "global_fetch_strictly_public",
]

[vars]

[[workers]]
name = "sanity-sync-webhook-worker"
main = "src/workers/sanity-sync-webhook.ts"